import numpy as np
from scipy.optimize import curve_fit

def bell_curve(x, a, x0, sigma):
    """Gaussian model for a single solar day."""
    return a * np.exp(-(x - x0)**2 / (2 * sigma**2))

def generate_report_data(date, rows, v_metrics, evaluate_formula, columns):
    """
    This function generates the daily report metrics.

    Parameters:
    - date: The date string (YYYY-MM-DD)
    - rows: The raw database rows for the given date (list of tuples/sqlite3.Row)
    - v_metrics: A dictionary of virtual metrics (name -> formula)
    - evaluate_formula: A function to evaluate virtual metrics: func(formula, data_dict)
    - columns: List of column names from the data_points table

    Returns:
    - A list of dictionaries, each representing a metric card for the frontend.

    Metric Card Dictionary Keys:
    - title:            The name shown at the top of the card.
    - value:            The main numerical or string value to display.
    - unit:             (Optional) The unit of measurement (e.g., 'Wh', '%').
    - html_description: The long-form explanation shown when the card is clicked/expanded.
    - description:      (Optional) Small sub-text shown immediately below the value.
    - status:           (Optional) Accent text indicating a state (e.g., 'Normal').
    - partial:          (Boolean) If True, a 'Partial Data' warning badge is displayed.
    - error:            (Optional) Error message to display if calculation fails.
    """

    # Pre-process data into NumPy arrays for easier calculation
    data_by_key = {col: [] for col in columns if col not in ('id', 'timestamp')}
    for vm_name in v_metrics:
        data_by_key[vm_name] = []

    timestamps = []
    for row in rows:
        row_dict = dict(zip(columns, row))
        # Evaluate virtual metrics for each row to allow them in calculations
        for name, formula in v_metrics.items():
            row_dict[name] = evaluate_formula(formula, row_dict)

        timestamps.append(row_dict['timestamp'])
        for key in data_by_key:
            data_by_key[key].append(row_dict.get(key))

    def get_clean_series(key):
        """Helper to get a numeric numpy array, replacing Nones with 0.0"""
        if key not in data_by_key: return np.zeros(len(timestamps))
        return np.array([float(x) if x is not None else 0.0 for x in data_by_key[key]])

    results = []
    # Standard day has 1440 minutely samples. We flag as partial if significantly fewer.
    is_partial = len(rows) < 1300

    # --- METRIC: Total Solar Yield ---
    pv_power = get_clean_series('pv_input_power')
    pv_wh = np.sum(pv_power) / 60
    results.append({
        "title":            "Total Solar Yield",
        "value":            round(pv_wh, 1),
        "unit":             "Wh",
        "partial":          is_partial,
        "html_description": "Total energy generated by your solar panels today."
    })

    # --- METRIC: Missed Solar Potential ---
    # Renamed from 'PV Power Clipping'.
    # This metric estimates energy lost when solar production is limited by inverter capacity.
    # We fit a Gaussian (bell) curve to the morning/afternoon data to predict the peak.
    missed_solar_report = {
        "title":            "Missed Solar Potential",
        "value":            "N/A",
        "unit":             "Wh",
        "partial":          is_partial,
        "html_description": "Solar energy lost because it exceeded your inverter's capacity. We estimate this by fitting a curve to your power data."
    }

    if len(pv_power) > 60:
        max_observed = np.max(pv_power)
        if max_observed > 10:
            times = np.arange(len(pv_power))
            # Use data between 15% and 80% of observed peak for curve fitting
            # to avoid using the clipped peak itself or noisy low-light data.
            mask = (pv_power > (max_observed * 0.15)) & (pv_power < (max_observed * 0.80))
            x_train = times[mask]
            y_train = pv_power[mask]

            if len(x_train) >= 60:
                try:
                    # p0: Initial guess [amplitude, center_index, sigma]
                    p0 = [max_observed * 1.1, np.argmax(pv_power), 150]
                    # bounds: Ensure the fit stays within reasonable physical limits
                    lower_bounds = [max_observed, 0, 50]
                    upper_bounds = [max_observed * 3, len(pv_power) * 1.5, 600]

                    popt, _ = curve_fit(bell_curve, x_train, y_train, p0=p0, bounds=(lower_bounds, upper_bounds))
                    theoretical_p = bell_curve(times, *popt)

                    # Energy difference between predicted curve and actual production
                    missed_w = np.maximum(0, theoretical_p - pv_power)
                    total_missed_wh = np.sum(missed_w) / 60

                    missed_solar_report.update({
                        "value":       round(total_missed_wh, 1),
                        "description": f"Actual Peak: {max_observed:.0f}W | Theoretical Peak: {popt[0]:.0f}W",
                        "status":      "Clipping Detected" if max_observed > popt[0] * 0.95 else "Normal"
                    })
                except Exception:
                    missed_solar_report["error"] = "Irregular data for curve fitting"
            else:
                missed_solar_report["error"] = "Insufficient active sun data"
        else:
            missed_solar_report.update({"value": 0, "status": "Night time / Low Power"})
    else:
        missed_solar_report["error"] = "Insufficient data points"

    results.append(missed_solar_report)

    # --- METRIC: Unstored Solar Usage ---
    # Renamed from 'Solar Self-Consumption'.
    # Measures the percentage of solar power consumed directly by the load
    # instead of being stored in the battery.
    batt_charge = get_clean_series('battery_charging_current') * get_clean_series('battery_voltage')
    charge_wh = np.sum(batt_charge) / 60

    unstored_usage = {
        "title":            "Unstored Solar Usage",
        "value":            "N/A",
        "unit":             "%",
        "partial":          is_partial,
        "html_description": "The percentage of solar energy used directly by your home as it was generated, instead of charging the battery."
    }
    if pv_wh > 10:
        direct_wh = max(0, pv_wh - charge_wh)
        ratio = (direct_wh / pv_wh) * 100
        unstored_usage["value"] = round(min(100, ratio), 1)
    results.append(unstored_usage)

    # --- METRIC: Battery Efficiency ---
    batt_disch = get_clean_series('battery_discharge_current') * get_clean_series('battery_voltage')
    disch_wh = np.sum(batt_disch) / 60
    batt_eff = {
        "title":            "Battery Efficiency",
        "value":            "N/A",
        "unit":             "%",
        "partial":          is_partial,
        "html_description": "How much energy you got back out of the battery compared to what you put in today."
    }
    if charge_wh > 10:
        eff = (disch_wh / charge_wh) * 100
        batt_eff["value"] = round(min(100, eff), 1)
    results.append(batt_eff)

    # --- METRIC: Solar Harvest Efficiency ---
    solar_predict = get_clean_series('solar_prediction')
    predicted_wh = np.max(solar_predict) if len(solar_predict) > 0 else 0
    harvest_eff = {
        "title":            "Solar Harvest Efficiency",
        "value":            "N/A",
        "unit":             "%",
        "partial":          is_partial,
        "html_description": "How your actual solar generation compared to the forecast."
    }
    if predicted_wh > 10 and pv_wh > 0:
        h_ratio = (pv_wh / predicted_wh) * 100
        harvest_eff["value"] = round(h_ratio, 1)
    results.append(harvest_eff)

    # --- METRIC: Peak Load Hour ---
    load_power = get_clean_series('ac_output_active_power')
    peak_load_hour = {
        "title":            "Peak Load Hour",
        "value":            "N/A",
        "unit":             "",
        "partial":          is_partial,
        "html_description": "The hour of the day when your home used the most electricity."
    }
    if len(load_power) > 60:
        hourly_loads = []
        for h in range(24):
            h_start = f"{date} {h:02d}:00:00"
            h_end = f"{date} {h:02d}:59:59"
            mask = [(ts >= h_start and ts <= h_end) for ts in timestamps]
            if any(mask):
                avg_l = np.mean(load_power[mask])
                hourly_loads.append((h, avg_l))
        if hourly_loads:
            best_h, val = max(hourly_loads, key=lambda x: x[1])
            peak_load_hour["value"] = f"{best_h:02d}:00"
            peak_load_hour["description"] = f"Avg load: {val:.0f}W"
    results.append(peak_load_hour)

    # --- METRIC: Energy Source: AC Input ---
    ac_input = get_clean_series('ac_input_active_power')
    ac_wh = np.sum(ac_input) / 60
    total_in_wh = ac_wh + pv_wh + disch_wh
    grid_dep = {
        "title":            "Energy Source: AC Input",
        "value":            "N/A",
        "unit":             "%",
        "partial":          is_partial,
        "html_description": "The percentage of your total energy that came from the grid or a generator."
    }
    if total_in_wh > 10:
        dep_ratio = (ac_wh / total_in_wh) * 100
        grid_dep["value"] = round(dep_ratio, 1)
    results.append(grid_dep)

    # HOW TO ADD AN ADDITIONAL METRIC:
    # -------------------------------
    # 1. Calculate your metric's value. Use 'get_clean_series(key)' to get a numpy array
    #    of any database key or virtual metric.
    # 2. Define a dictionary for your metric following the schema in the function docstring.
    # 3. Append your new dictionary to the 'results' list.
    #
    # Example:
    # results.append({
    #     "title": "My New Metric",
    #     "value": 42,
    #     "unit": "units",
    #     "html_description": "Explanation of what this metric represents."
    # })

    return results
